version: 2.1

orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@1.2

jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm test

  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - heroku/deploy-via-git:
          force: true

workflows:
  version: 2
  sample:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: /.*-heroku-deploy/ # Adjust this filter as needed
              # only: master  # Uncomment this line if you want to restrict to master